apiVersion: v1
kind: Pod
metadata:
  name: podwithcmvol
  labels:
    name: myapp
spec:
  volumes:
    - name: cmvol
      configMap:
          name: cm1-cli
  containers:
  - name: container1
    image: salman079/hello-world-kids
    volumeMounts:
      - mountPath: /data/cm
        name: cmvol
    imagePullPolicy: IfNotPresent
