kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100M
  hostPath:
    path: /tmp/pvexample
  persistentVolumeReclaimPolicy: Delete