apiVersion: v1
kind: Pod
metadata:
  name: pod-pv
spec:
  volumes:
  - name: pv-vol1
    persistentVolumeClaim:
      claimName: pvc
  containers:
  - name: container1
    image: aamirpinger/logfile_nodejs
    volumeMounts:
    - name: pv-vol1
      mountPath: /data